//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KWZP_lab_23_04
{
    using System;
    using System.Collections.Generic;
    
    public partial class Etapy_W_Procesie
    {
        public int ID_Etapy_W_Procesie { get; set; }
        public int ID_Proces_Technologiczny { get; set; }
        public int ID_Etapu { get; set; }
        public int Czas { get; set; }
    
        public virtual Rodzaj_Etapu Rodzaj_Etapu { get; set; }
        public virtual Proces_Technologiczny Proces_Technologiczny { get; set; }
    }
}
