//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KWZP_lab_23_04
{
    using System;
    using System.Collections.Generic;
    
    public partial class Umowy_Kurierzy
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Umowy_Kurierzy()
        {
            this.Zamowienia_Przydzial = new HashSet<Zamowienia_Przydzial>();
        }
    
        public int ID_Umowy { get; set; }
        public string ID_Kurier { get; set; }
        public Nullable<System.DateTime> Data_Zawarcia { get; set; }
        public Nullable<System.TimeSpan> Czas_Dostawy { get; set; }
        public Nullable<int> Koszt_Km { get; set; }
        public Nullable<int> Koszt_Staly { get; set; }
    
        public virtual Kurierzy Kurierzy { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Zamowienia_Przydzial> Zamowienia_Przydzial { get; set; }
    }
}
