//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KWZP_lab_23_04
{
    using System;
    using System.Collections.Generic;
    
    public partial class vZatrudnienie
    {
        public int ID_Pracownika { get; set; }
        public float Pensja { get; set; }
        public string Stanowisko { get; set; }
        public System.DateTime Start_umowy { get; set; }
        public System.DateTime Koniec_umowy { get; set; }
    }
}
