//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KWZP_lab_23_04
{
    using System;
    using System.Collections.Generic;
    
    public partial class Zamowienia_Zawartosc
    {
        public int ID_Zamowienia_Zawartosc { get; set; }
        public Nullable<int> ID_Zamowienia { get; set; }
        public Nullable<int> ID_Oferta { get; set; }
        public Nullable<int> Ilosc_Zamawiana { get; set; }
    
        public virtual Oferta Oferta { get; set; }
        public virtual Zamowienia Zamowienia { get; set; }
    }
}
