//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KWZP_lab_23_04
{
    using System;
    using System.Collections.Generic;
    
    public partial class Znajomosc_Jezykow
    {
        public int ID_Znajomosc_Jezykow { get; set; }
        public Nullable<int> ID_Jezyka { get; set; }
        public Nullable<int> ID_Pracownika { get; set; }
    
        public virtual Jezyk Jezyk { get; set; }
        public virtual Pracownicy Pracownicy { get; set; }
    }
}
